export enum STATUS_MASTER {
  REQUIRED = 1,
  WAITING = 2,
  PENDING = 3,
  REJECTED = 4,
  CLOSED = 5,
  EXPIRED = 6,
  REGISTERED = 7,
  ACTIVATED = 8,
  PROCESSING = 9,
  COMPLETED = 10,
  MATCHED = 11,
  UN_MATCHED = 12,
  UN_SUBMITTED = 13,
  SCHEDULED = 14,
  DRAFT = 15,
  SUBMITTED = 16,
  APPROVED = 17,
  CANCELLED = 18,
  BLOCKED = 19,
  UN_ACTIVE = 20,
  UN_GROUPED = 21, // chưa vào nhóm, nếu vào nhóm rồi thì sử dụng STATUS_MASTER.ACTIVATED
  AVAILABLE = 22, // supervisor chưa đủ nhóm, nếu supervisor đủ nhóm rồi thì sử dụng STATUS_MASTER.ACTIVATED
  PASS = 23,
  FAILED = 24
}

export enum USER_STATUS {
  CLOSED = STATUS_MASTER.CLOSED,
  REGISTERED = STATUS_MASTER.REGISTERED,
  BLOCKED = STATUS_MASTER.BLOCKED,
  UN_ACTIVE = STATUS_MASTER.UN_ACTIVE,
  ACTIVATED = STATUS_MASTER.ACTIVATED,
  UN_GROUPED = STATUS_MASTER.UN_GROUPED,
  AVAILABLE = STATUS_MASTER.AVAILABLE
}

export enum ACCOUNT_STATUS {
  CLOSED = STATUS_MASTER.CLOSED,
  REGISTERED = STATUS_MASTER.REGISTERED,
  BLOCKED = STATUS_MASTER.BLOCKED,
  UN_ACTIVE = STATUS_MASTER.UN_ACTIVE,
  ACTIVATED = STATUS_MASTER.ACTIVATED
}

export enum PROJECT_STATUS {
  PENDING = STATUS_MASTER.PENDING, //chưa đủ member hoặc chưa có gv
  ACTIVATED = STATUS_MASTER.ACTIVATED, //đủ member và đã có gv
  REJECTED = STATUS_MASTER.REJECTED, //đề tài bị GV reject
  APPROVED = STATUS_MASTER.APPROVED, //đề tài đủ đk để làm
  SUBMITTED = STATUS_MASTER.SUBMITTED, //đã submit đủ, đủ đk để bảo vệ
  PASSED = STATUS_MASTER.PASS, //sau khi có điểm, pass
  FAILED = STATUS_MASTER.FAILED //sau khi có điểm, fail
}
