version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    environment:
      - REDIS_HOST=localhost
      - REDIS_PORT=6379

networks:
  default:
    name: redis_queue_network
