name: Node.js CI

on:
  push:
    branches: ["develop", "staging", "production"]
  pull_request:
    branches: ["develop", "staging", "production"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.17.0]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: cd client
      - run: yarn
      - run: yarn build
